project:
  type: website
  output-dir: docs

website:
  title: "Pranav Kolluri"
  site-url: https://pranavkolluri.dev
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: visualization.qmd
        text: Visualization

resources:
  - CNAME

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body: email-obfuscate.html
